### ISSUE TITLE
你好，我想问一下目前cityscapes这个数据集能跑吗？如果不能跑具体是什么问题呢？

### ISSUE THREAD

**Issue by Ultraman6** [youngfish42/FMTL-Benchmark#2]

**Comment by Ultraman6** [comment]
这里为什么有三种维度？
含义我知道分别是原始样本维度、期望标签维度以及训练维度
可是为什么必须把训练维度设置成这么难处理的数字？

![image](https://github.com/user-attachments/assets/071ed9d0-9976-4bf3-b82d-5499301361f8)
![image](https://github.com/user-attachments/assets/57c326d6-9cfd-47d5-8710-bf3c7edbe6ca)
![image](https://github.com/user-attachments/assets/23abc1ab-3bf0-4a48-a498-b96b2401f915)

**Comment by rG223** [comment]
@Ultraman6 请问你可以跑pascal_context数据集吗？我在官网下的数据集跟作者的数据目录不一样，作者用"splits_dir = os.path.join(self.root, 'ImageSets/Context')"  但是我下载的数据目录只到ImageSets 下面没有Context这个文件夹

**Comment by youngfish42** [comment]
抱歉才看到~
原实验中只进行了pascal_context 和 nyud数据集的实验，尚未测试关于 cityscapes 数据集的部分
